on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.5
        ports:
          - 2379:2379
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      consul:
        image: hashicorp/consul:1.18
        ports:
          - 8500:8500
      vault:
        image: hashicorp/vault:1.15
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - name: Test
        run: make test
